version: '3.8'
services:
    shopit:
        container_name: shopit
        restart: always
        build: .
        ports:
            - '4000:4000'
        links:
            - ordersDB
            - usersDB
    ordersDB:
        container_name: ordersDB
        image: mongo:4.4.6
        volumes:
            - mongo-data:/data/db
        ports:
            - '27017:27017'
    usersDB:
        container_name: usersDB
        image: postgres:13.3
        env_file:
            - .env
        volumes:
            - postgres-data:/var/lib/postgresql/data/
volumes:
    mongo-data:
    postgres-data:
