version: '3.8'
services:
    shopit:
        container_name: shopit
        restart: always
        build: .
        ports:
            - '3000:3000'
        links:
            - ordersDB
            - usersDB
    ordersDB:
        container_name: ordersDB
        image: mongo:4.4.6
        volumes:
            - ./data/mongo:/data/db
        ports:
            - '27017:27017'
    usersDB:
        container_name: usersDB
        image: postgres:13.3
        env_file:
            - .env
        volumes:
            - data/postgres:/var/lib/postgresql/data/
